name = "digital-listings"
pages_build_output_dir = "dist/public"
compatibility_date = "2024-04-03"
command = "npm run build"

[[d1_databases]]
binding = "DB"
database_name = "digital-listings-db"
database_id = "b30228ec-298e-41d6-9b26-e305a5e50332"
